import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    backgroundColor: '#202124',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    width: 400,
    backgroundColor: '#2b2c2f',
    borderRadius: 12,
    padding: '40px 32px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.3)',
  },
  header: {
    textAlign: 'center' as const,
    marginBottom: 32,
  },
  icon: {
    fontSize: 48,
    color: '#8ab4f8',
    marginBottom: 16,
  },
  title: {
    color: '#e8eaed',
    fontSize: 24,
    fontWeight: 500,
    margin: 0,
  },
  subtitle: {
    color: '#9aa0a6',
    fontSize: 14,
    marginTop: 8,
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 16,
  },
  input: {
    backgroundColor: '#35363a',
    border: '1px solid #3c4043',
    borderRadius: 8,
    padding: '12px 16px',
    color: '#e8eaed',
    fontSize: 14,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  inputFocus: {
    borderColor: '#8ab4f8',
  },
  button: {
    backgroundColor: '#8ab4f8',
    color: '#171717',
    border: 'none',
    borderRadius: 8,
    padding: '12px 24px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    width: '100%',
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  link: {
    color: '#8ab4f8',
    cursor: 'pointer',
    textAlign: 'center' as const,
    marginTop: 16,
    fontSize: 14,
  },
  error: {
    backgroundColor: 'rgba(255,77,79,0.1)',
    border: '1px solid #ff4d4f',
    borderRadius: 8,
    padding: '12px 16px',
    color: '#ff4d4f',
    fontSize: 13,
    marginBottom: 8,
  },
  passwordHint: {
    color: '#9aa0a6',
    fontSize: 12,
    marginTop: -8,
  },
  passwordWrapper: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
  },
  passwordInput: {
    backgroundColor: '#35363a',
    border: '1px solid #3c4043',
    borderRadius: 8,
    padding: '12px 40px 12px 16px',
    color: '#e8eaed',
    fontSize: 14,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  eyeButton: {
    position: 'absolute' as const,
    right: 12,
    background: 'none',
    border: 'none',
    color: '#9aa0a6',
    cursor: 'pointer',
    padding: 0,
    fontSize: 16,
    display: 'flex',
    alignItems: 'center',
  },
};
