import type { CSSProperties } from 'react';
import { colors } from '../../../../shared/styles/colors';

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    backgroundColor: colors.backgroundDark,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    width: 400,
    backgroundColor: colors.backgroundContainer,
    borderRadius: 12,
    padding: '40px 32px',
    boxShadow: '0 0 0 1px rgba(255,255,255,0.06), 0 4px 24px rgba(0,0,0,0.4)',
  },
  header: {
    textAlign: 'center' as const,
    marginBottom: 32,
  },
  icon: {
    fontSize: 48,
    color: colors.primaryBlue,
    marginBottom: 16,
  },
  title: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: 500,
    margin: 0,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: 8,
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 16,
  },
  input: {
    backgroundColor: colors.backgroundElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    padding: '12px 16px',
    color: colors.textPrimary,
    fontSize: 14,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  inputFocus: {
    borderColor: colors.primaryBlue,
  },
  button: {
    backgroundColor: colors.primaryBlue,
    color: colors.backgroundDarkest,
    border: 'none',
    borderRadius: 8,
    padding: '12px 24px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    width: '100%',
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  link: {
    color: colors.primaryBlue,
    cursor: 'pointer',
    textAlign: 'center' as const,
    marginTop: 16,
    fontSize: 14,
  },
  error: {
    backgroundColor: 'rgba(255,77,79,0.1)',
    border: `1px solid ${colors.errorRed}`,
    borderRadius: 8,
    padding: '12px 16px',
    color: colors.errorRed,
    fontSize: 13,
    marginBottom: 8,
  },
  passwordHint: {
    color: colors.textSecondary,
    fontSize: 12,
    marginTop: -8,
  },
  passwordWrapper: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
  },
  passwordInput: {
    backgroundColor: colors.backgroundElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: 8,
    padding: '12px 40px 12px 16px',
    color: colors.textPrimary,
    fontSize: 14,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  eyeButton: {
    position: 'absolute' as const,
    right: 12,
    background: 'none',
    border: 'none',
    color: colors.textSecondary,
    cursor: 'pointer',
    padding: 0,
    fontSize: 16,
    display: 'flex',
    alignItems: 'center',
  },
};
