import type { CSSProperties } from 'react';
import { colors } from '../../../../../shared/styles/colors';
import { disabledStates, transitions } from '../../../../../shared/styles/states';

export const styles: Record<string, CSSProperties> = {
  button: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: `2px solid ${colors.textSecondary}`,
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
    transition: `all ${transitions.fast}`,
  },
  buttonChecked: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: 'none',
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
    transition: `all ${transitions.fast}`,
  },
  buttonDisabled: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: `2px solid ${colors.textSecondary}`,
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: disabledStates.cursor,
    padding: 0,
    opacity: disabledStates.opacity,
    transition: `all ${transitions.fast}`,
  },
  buttonCheckedDisabled: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: 'none',
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: disabledStates.cursor,
    padding: 0,
    opacity: disabledStates.opacity,
    transition: `all ${transitions.fast}`,
  },
  checkIcon: {
    color: colors.textWhite,
    fontSize: 16,
  },
};
